# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'chmp' -Path (Join-Path (Join-Path $toolsDir 'bin') 'chmp.bat')
Install-BinFile -Name 'counter' -Path (Join-Path (Join-Path $toolsDir 'bin') 'counter.bat')
Install-BinFile -Name 'lag' -Path (Join-Path (Join-Path $toolsDir 'bin') 'lag.bat')
Install-BinFile -Name 'lol' -Path (Join-Path (Join-Path $toolsDir 'bin') 'lol.bat')
